### ISSUE TITLE
Create `PackagedServices` model

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/setlife-solutions#72]
Table `service_package_service` model
Attributes
```
* service_id
* service_package_id
```
Where `service_id` and `service_package_id` are a composite key

**Comment by sofiaromorales** [comment]
@Ovifer13 can you think of a better name for this table?

**Comment by Ovifer13** [comment]
`sps_package_service`, `s_package_s`

**Comment by otech47** [comment]
I recommend PackagedServices for this model. Makes sense to me

Also @Ovifer13 I would avoid abbreviations in database table names since they might be misunderstood to mean anything and don't add much descriptive value to the database table

Always think of what a future developer might think when reading table names and other code
